---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin-deployment
spec:
  selector:
    matchLabels:
      app: httpbin
  replicas: 2
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
      - name: httpbin
        image: nsustain/maintenance-page:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: httpbin
  ports:
    - protocol: TCP
      port: 80

# "Deployments are designed for stateless applications ...
# StatefulSets are the recommended method of deploying stateful
# applications that require a unique volume per replica. By using
# StatefulSets with PersistentVolumeClaim templates, you can have
# applications that can scale up automatically with unique
# PersistentVolumesClaims associated to each replica Pod."
# Source:
#   https://cloud.google.com/kubernetes-engine/docs/concepts/persistent-volumes#deployments_vs_statefulsets
