# ----------------------------------------------------------
# 
# ----------------------------------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: flarum-secret
type: Opaque
stringData:
  password: test
  admin-password: test
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
stringData:
  password: test
  admin-password: test
