apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: flarum-data
  name: flarum-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: flarum-service
spec:
  selector:
    app: flarum
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flarum-deployment
spec:
  selector:
    matchLabels:
      app: flarum
  replicas: 2
  template:
    metadata:
      labels:
        app: flarum
    spec:
      containers:
      - name: flarum
        image: nsustain/maintenance-page:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: flarum-data
      volumes:
        - name: flarum-data
          persistentVolumeClaim:
            claimName: flarum-data
