# ------------------------------------------------------------------
# This file specifies what happens when we run
# "docker compose up -d ..."
#
# After running the Compose file, go to http://127.0.0.1 to access
# your development server. Note that http://localhost is incorrect,
# and only http://127.0.0.1 is designed to work.
# ------------------------------------------------------------------
services:
  flarum:
    image: soobinrho/test:latest
    # image: nsustain/flarum:latest
    container_name: flarum
    depends_on:
      - mariadb
    ports:
      - 80:80
    expose:
      - 9000
    networks:
      - back-end
    environment:
      # We included randomized secrets here so that you can can run
      # our image out of the box without any extra configuration.
      # Use these env variables just for development environments.
      # Never use these in production environments.
      - DEBUG=false
      - FORUM_URL=http://127.0.0.1
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_NAME=flarum
      - DB_USER=flarum
      - DB_PASS=qdKiSiEPxVuFggmN3s5B9ubno4h3QUy5f3S6EAZ9o9
      - DB_PREF=flarum_
      - FLARUM_ADMIN_USER=nim3594
      - FLARUM_ADMIN_PASS=369FQUv4eS
      - FLARUM_ADMIN_MAIL=dev@nsustain.com
      - FLARUM_DESCRIPTION=A forum created for the environment and sustainability.
      - FLARUM_TITLE=Nsustain Development Server
      - FLARUM_WELCOME_MESSAGE=🌳 For the environment and sustainability.
      - FLARUM_WELCOME_TITLE=Nsustain
      - FLARUM_EXTENSIONS_ENABLED=["flarum-flags","flarum-tags","flarum-suspend","flarum-subscriptions","flarum-sticky","flarum-statistics","flarum-mentions","flarum-markdown","flarum-lock","flarum-likes","flarum-lang-english","flarum-emoji","flarum-bbcode","flarum-approval","fof/oauth","fof/nightmode","datlechin/flarum-link-preview","clarkwinkelmann/flarum-ext-shdow-ban","v17development/flarum-third-party-login-only"]
    volumes:
      # Normally, config files are added inside the container
      # directly at Dockerfile, but these three files are mounted
      # as volumes at this Compose file because we sometimes have to
      # change the values of these files for testing purposes.
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./www.conf:/etc/php8/php-fpm.d/www.conf
      - ./composer.json:/var/www/html/flarum/composer.json

      # These preserve the state of Flarum each time we restart our Docker image.
      # Example location of named volumes:
      #   /var/lib/docker/volumes/docker_flarum-assets
      - flarum-assets:/var/www/html/flarum/public/assets
      - flarum-storage:/var/www/html/flarum/storage

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    expose:
      - 3306
    networks:
      - back-end
    restart: always
    environment:
      # Again, these are randomized secrets just for
      # development environments. In your production environments,
      # you should never use these env variables.
      - MARIADB_ROOT_PASSWORD=TTBXkgeu25GVyge8FQrZBPj7HYiuG9qCawRcff5ukP
      - MARIADB_DATABASE=flarum
      - MARIADB_USER=flarum
      - MARIADB_PASSWORD=qdKiSiEPxVuFggmN3s5B9ubno4h3QUy5f3S6EAZ9o9
    volumes:
      - mariadb-data:/var/lib/mysql

volumes:
  flarum-assets:
  flarum-storage:
  mariadb-data:

# "The presence of these objects is sufficient to define them"
# Source:
#   https://docs.docker.com/compose/compose-file/
networks:
  back-end: {}
