# ------------------------------------------------------------------
# This file specifies what happens when we run
# "docker compose up -d ..."
#
# After running the Compose file, go to http://127.0.0.1 to access
# your development server. Note that http://localhost is incorrect,
# and only http://127.0.0.1 is designed to work.
# ------------------------------------------------------------------
services:
  flarum:
    image: nsustain/flarum:latest
    pull_policy: missing
    container_name: flarum
    # Always restart the container, even after rebooting the host
    restart: always
    # Since this container doesn't accept SIGTERM, we use
    # stop_grace_period: 1s to send SIGKILL after 1s
    stop_grace_period: 1s
    depends_on:
      - mariadb
    ports:
      - 80:80
    expose:
      - 9000
    networks:
      - back-end
    volumes:
      # Normally, config files are added inside the container
      # directly at Dockerfile, but these three files are mounted
      # as volumes at this Compose file because we sometimes have to
      # change the values of these files for testing purposes.
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./www.conf:/etc/php8/php-fpm.d/www.conf
      - ./composer.json:/var/www/html/flarum/composer.json:rw
      - ./composer.lock:/var/www/html/flarum/composer.lock:rw

      # These preserve the state of Flarum each time we restart our Docker image.
      # Example location of named volumes:
      #   /var/lib/docker/volumes/docker_flarum-assets
      - flarum-assets:/var/www/html/flarum/public/assets
      - flarum-storage:/var/www/html/flarum/storage
      - flarum-vendor:/var/www/html/flarum/vendor

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    expose:
      - 3306
    networks:
      - back-end
    environment:
      # Again, these are randomized secrets just for
      # development environments. In your production environments,
      # you should never use these env variables.
      - MARIADB_ROOT_PASSWORD=TTBXkgeu25GVyge8FQrZBPj7HYiuG9qCawRcff5ukP
      - MARIADB_DATABASE=flarum
      - MARIADB_USER=flarum
      - MARIADB_PASSWORD=qdKiSiEPxVuFggmN3s5B9ubno4h3QUy5f3S6EAZ9o9
    volumes:
      - mariadb-data:/var/lib/mysql

volumes:
  flarum-assets:
  flarum-storage:
  flarum-vendor:
  mariadb-data:

# "The presence of these objects is sufficient to define them"
# Source:
#   https://docs.docker.com/compose/compose-file/
networks:
  back-end: {}
