# ----------------------------------------------------------------
# WHAT IS THIS FILE FOR?
# Using docker compose is one of two ways we deploy Nsustain.com
# If you're running it on one host, use docker compose.
# If you're running it on two or more hosts for high availability,
# use kubernetes.
# ----------------------------------------------------------------

# We use Compose Version 3.3 because it's the recommended version
# by Kompose, which automatically converts Compose files into
# Kubernetes objects.
# Source:
#   https://kompose.io/conversion/#version-table
version: "3.3"
services:
  flarum:
    image: nsustain/flarum:latest
    container_name: flarum
    # Always restart the container, even after reboot
    restart: always
    # Since this container doesn't accept SIGTERM, we use
    # stop_grace_period: 0.5s to send SIGKILL after 0.5s
    stop_grace_period: 0.5s
    depends_on:
      - mariadb
    ports:
      - 80:80
      - 443:443
    expose:
      - 9000  # used by PHP-FPM
    networks:
      - back-end
    volumes:
      # These are the data files for the container.
      # Location of these files:
      #   /var/lib/docker/volumes/...
      - flarum-data:/var/www/html/flarum
      - nginx-conf:/etc/nginx

      # When you first run our image, these volumes will
      # be empty. Howver, if you'd like to set up https / SSL,
      # these volumes will be used for storing the certificates.
      - /etc/letsencrypt:/etc/letsencrypt

      # certbot uses lock-files system for its internal functions.
      # Source:
      #   https://eff-certbot.readthedocs.io/en/stable/using.html#where-certs
      - /var/lib/letsencrypt:/var/lib/letsencrypt

    # Uncomment to override default env variables with your own.
    # This is not required in development environments, but
    # in production environments, this is recommeneded.
    #env_file:
    #  - .envflarum

  mariadb:
    image: nsustain/mariadb:latest
    container_name: mariadb
    restart: always
    expose:
      - 3306  # used by MariaDB
    networks:
      - back-end
    volumes:
      - mariadb-data:/var/lib/mysql
    # Uncomment to override default env variables with your own
    #env_file:
    #  - .envmariadb

volumes:
  flarum-data:
  nginx-conf:
  mariadb-data:

# "The presence of these objects is sufficient to define them"
# Source:
#   https://docs.docker.com/compose/compose-file/
networks:
  back-end: {}
