apiVersion: v1
kind: Pod
metadata:
  name: mariadb
  namespace: default
  labels:
    app: mariadb
spec:
  containers:
  - name: mariadb
    image: mariadb:latest
    ports:
    - containerPort: 3306
      name: mariadb-port
  restartPolicy: Always
---

