apiVersion: v1
kind: Pod
metadata:
  name: vault
  namespace: default
  labels:
    app: vault
spec:
  containers:
  - name: vault
    image: hashicorp/vault-k8s:latest
    ports:
    - containerPort: 8200
      name: vault-port
  restartPolicy: Always
---

